sudo: true
dist: trusty
language: node_js
node_js:
  - '6.7.0'
  - '4.2.1'
addons:
  firefox: "latest"
before_install:
  - 'npm config get registry'
  - 'npm config set registry http://registry.npmjs.org/'
  - 'export CHROME_BIN=/usr/bin/google-chrome'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'sleep 3'
  - 'sudo apt-get update'
  - 'sudo apt-get install -y libappindicator1 fonts-liberation'
  - 'wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
  - 'sudo dpkg -i google-chrome*.deb'
install:
  - 'npm install --global grunt-cli bower yo generator-karma generator-angular'
  - 'npm install karma jasmine-core'
  - 'sudo apt-get install -y ruby ruby-dev make'
  - 'gem install compass'
  - 'npm update'
  - 'bower update'
  - 'node_modules/protractor/bin/webdriver-manager update --standalone --firefox'
  - 'sleep 5'
  - 'node_modules/grunt-protractor-runner/scripts/webdriver-manager-update'
  - 'sleep 5'
after_script:
- cat ./build/coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success: grunt coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
